version: '3'

services:
  db:
    image: mongo:4.1.13
    container_name: db
    networks:
      - net_A
    volumes:
      - mongo_data:/data/db
    ports:
      - '27019:27017'

  server:
    build: .
    container_name: server
    depends_on:
      - db
    networks:
      - net_A
    ports:
      - '3003:3000'

networks:
  net_A:

volumes:
  mongo_data:
